spring.application.name=hrProcessAutomation

server.port=${PORT:8080}


# -----------------------
# Aiven MySQL Datasource
# -----------------------
#spring.datasource.url=jdbc:mysql://hrprocessessautomation-hrprojectautomation.j.aivencloud.com:16859/defaultdb?useSSL=true&requireSSL=true
#spring.datasource.username=avnadmin
#spring.datasource.password=spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# SSL Configuration (using Aiven CA certificate)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.tomcat.ssl=true
spring.datasource.tomcat.sslTrustStore=classpath:ca.pem
spring.datasource.tomcat.sslTrustStorePassword=changeit

# Optional: Connection Pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tyroads.global@gmail.com
spring.mail.password=tugfjapfhejvjbuh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

